<<<<<<< HEAD
name: tests-orders

on:
  pull_request


jobs:
 build:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v2
      -  run: cd orders && npm install && npm run test:ci
     
       
=======
name: test-oredrs

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
>>>>>>> f396f7d22a5bdf666d3f432bbf3ff342dcfce4f3
